/**
 * Generate embedded assets imports
 * 
 * This script generates a TypeScript file that imports all frontend assets
 * using `import ... with { type: "file" }` syntax for embedding in the binary.
 */

import { Glob } from "bun";
import { join, resolve, relative, basename, dirname } from "node:path";
import { existsSync, writeFileSync, rmSync } from "node:fs";

const ROOT = resolve(import.meta.dir, "..");
const APP_DIST = join(ROOT, "packages/app/dist");
const OUTPUT = join(ROOT, "packages/server/src/generated-assets.ts");

console.log("📝 Generating embedded assets imports...");

// Collect all files
const assetGlob = new Glob("**/*");
const files = Array.from(assetGlob.scanSync(APP_DIST))
  .filter(f => !f.endsWith("/")); // Filter out directories

console.log(`   Found ${files.length} files`);

// Generate imports
const imports: string[] = [];
const exports: string[] = [];

for (const file of files) {
  const fullPath = join(APP_DIST, file);
  const varName = `asset_${file.replace(/[^a-zA-Z0-9]/g, "_")}`;
  const importPath = `../../app/dist/${file}`;
  
  imports.push(
    `import ${varName} from "${importPath}" with { type: "file" };`
  );
  exports.push(`  "${file}": ${varName},`);
}

// Generate the file content
const content = `/**
 * Auto-generated embedded assets
 * DO NOT EDIT - generated by scripts/generate-assets.ts
 * 
 * This file imports all frontend assets for embedding in the binary.
 * Each import uses \`with { type: "file" }\` to embed the file contents.
 */

${imports.join("\n")}

/**
 * Map of embedded asset paths to their embedded file paths
 * 
 * Key: relative path from app/dist (e.g., "index.html", "assets/index-xxx.js")
 * Value: embedded file path (e.g., "$bunfs/index-xxx.html")
 */
export const embeddedAssets: Record<string, string> = {
${exports.join("\n")}
};

/**
 * Check if we have embedded assets
 */
export function hasEmbeddedAssets(): boolean {
  return Object.keys(embeddedAssets).length > 0;
}

/**
 * Get embedded asset path by relative path
 */
export function getEmbeddedAsset(path: string): string | null {
  return embeddedAssets[path] ?? null;
}

/**
 * List all embedded asset paths
 */
export function listEmbeddedAssets(): string[] {
  return Object.keys(embeddedAssets);
}
`;

writeFileSync(OUTPUT, content);
console.log(`   Generated: ${OUTPUT}`);
